remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# サイト情報
title: あなたのサイトタイトル
description: サイトの簡潔な説明

# オプション設定
show_downloads: false  # ダウンロードボタンを表示する場合はtrue
google_analytics: # Google AnalyticsのIDがあれば記入
